openapi: 3.0.1
info:
  title: demoAPI
  version: v1
  host: carbide-ward-303004.appspot.com
paths:
  /Location:
    get:
      tags:
        - Location
      responses:
        '200':
          description: Success
    post:
      tags:
        - Location
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Location'
          text/json:
            schema:
              $ref: '#/components/schemas/Location'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Location'
      responses:
        '200':
          description: Success
  '/Location/{id}':
    get:
      tags:
        - Location
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  /WeatherForecast:
    get:
      tags:
        - WeatherForecast
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
    post:
      tags:
        - WeatherForecast
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WeatherForecast'
      responses:
        '201':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/WeatherForecast'
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherForecast'
            text/json:
              schema:
                $ref: '#/components/schemas/WeatherForecast'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  '/WeatherForecast/{id}':
    get:
      tags:
        - WeatherForecast
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    delete:
      tags:
        - WeatherForecast
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
components:
  schemas:
    Location:
      type: object
      properties:
        id:
          type: integer
          format: int32
        location_name:
          type: string
          nullable: true
        updated_at:
          type: string
          format: date-time
      additionalProperties: false
    WeatherForecast:
      type: object
      properties:
        id:
          type: integer
          format: int32
        date:
          type: string
          format: date-time
        temperatureC:
          type: integer
          format: int32
        temperatureF:
          type: integer
          format: int32
          readOnly: true
        summary:
          type: string
          nullable: true
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}
